### ISSUE TITLE
Snap package is not working on Arch (KDE)

### ISSUE THREAD

**Issue by waredrive** [jochy/mod-updater#27]
Snap package throws the following errors when launched:

16:53:28.473 › 
16:53:28.476 › ----- New start -----
16:53:28.476 › Current TZ=undefined ; changing it to UTC
Gtk-Message: 15:53:28.527: Failed to load module "xapp-gtk3-module"
Gtk-Message: 15:53:28.552: Failed to load module "colorreload-gtk-module"
Gtk-Message: 15:53:28.552: Failed to load module "window-decorations-gtk-module"
[1116/155328.577251:ERROR:scoped_ptrace_attach.cc(27)] ptrace: Operation not permitted (1)
zsh: trace trap (core dumped)  sims-mod-updater

**Comment by jochy** [comment]
Hi,

This is a known issue, caused by the cache library I'm using. I'm currently trying to replace it in order to fix this issue

**Comment by jochy** [comment]
Hi, 

I worked on it and managed to make it work on my computer. Can you install the snap package here and let me know if it's OK : https://github.com/jochy/mod-updater/releases/download/2.6.3/sims-mod-updater.snap 

You can install it using this command line : `snap install sims-mod-updater.snap --classic --dangerous` (`dangerous` param is to tell you that this file is not uploaded on snap repo).

If it works, then I'll be able to work with the Snap team to let me upload the package with `classic` confinement, so you'll be able to install the app directly from the official repo.

**Comment by waredrive** [comment]
Hi,
I've installed the updater now and it seems to be working, although I needed to setup a snap symlink to run the classic argument (sudo ln -s /var/lib/snapd/snap /snap) .
I also get an error regarding unar package not being installed. I've checked the AUR repository and it seems that the unar package is not present there. There is though an "unarchiver" package (which I have install but still getting the error) and "unarj" package, so that needs to be changed I guess:

06:27:09.876 › Error: Command failed: /run/user/1000/install-unar.sh
error: target not found: unar

    at checkExecSyncError (node:child_process:837:11)
    at execFileSync (node:child_process:872:15)
    at func (node:electron/js2c/asar_bundle:5:1812)
    at h (/var/lib/snapd/snap/sims-mods-updater/x1/usr/lib/sims-mods-updater/resources/app.asar/.webpack/main/858.js:1:2801)
    at Module.f (/var/lib/snapd/snap/sims-mods-updater/x1/usr/lib/sims-mods-updater/resources/app.asar/.webpack/main/858.js:1:1395)
    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async IpcMainImpl.<anonymous> (/var/lib/snapd/snap/sims-mods-updater/x1/usr/lib/sims-mods-updater/resources/app.asar/.webpack/main/index.js:2:3759)
06:27:09.877 › [InstallUnar] Error while checking unar installation, installing it, just in case...
06:27:09.880 › [InstallUnar] Need to run sudo pacman -S unar -y
06:27:09.880 › [InstallUnar] Creating installation file: /run/user/1000/install-unar.sh
error: target not found: unar
06:27:10.910 › Unable to install unrar Error: Command failed: /run/user/1000/install-unar.sh
error: target not found: unar

**Comment by jochy** [comment]
I fixed the issue with unar dependency (which is now included inside the snap package). 

Also, I managed to make it work in strict confinement, so you can now pull it from the official snap repo and you don't have to add `--classic`. 
The snap package file in the release has been updated : https://github.com/jochy/mod-updater/releases/download/2.6.3/sims-mod-updater.snap 

If you need something else, feel free to reopen this issue.

**Comment by waredrive** [comment]
Thanks, but I think the strict confinement is preventing the updater from creating files in the game directory. I get access error when creating mod versioning as the write access for the snap is forbidden.

**Comment by jochy** [comment]
Hmm, it worked on my computer and other users can use the snap package. I'll check if there is not something I must declare to make sure it behave the same on every computers
